# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
# Pantech SKY Switch Class Driver
obj-$(CONFIG_SWITCH_SKY)	+= switch_sky.o

obj-$(CONFIG_MACH_MSM8X60_EF39S)	+= pansw_class.o


